# https://taskfile.dev

version: '3'

# poetry shell
# source emsdk_env.sh
# cd ..

tasks:
  build/release:
    aliases: [br]
    cmds:
      - pyodide build --outdir dist/release
  build/debug:
    aliases: [bd]
    cmds:
      - CFLAGS=-g2 LDFLAGS=g2 pyodide build --outdir dist/debug
